name: Integración de Snyk con GitHub
on:
  push:
    branches: [main]


jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:

    #Comprobamos el código fuente   
    - name: Comprobar codigo fuente
      uses: actions/checkout@v3
    
    #Setup de node en el Runner
    - name: Setup de nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Java 17
      uses: actions/setup-java@v3
      with:
        #Declaramos la versión de Java deseada
        java-version: '17'

    - name: MVN
      run: |
        mvn spotless:apply 
        mvn -DskipTests=true install
        
    - name: Run Snyk to check for vulnerabilities
      uses: snyk/actions/maven@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
