name: Integración de Snyk con GitHub
on:
  push:
    branches: [main]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v2
    - name: maven clean
      run: mvn clean
    - name: maven instalacion
      run: mvn -DskipTests=true install
    - name: Instalar Snyk CLI
      run: npm install -g snyk
    - name: Analizar vulnerabilidades
      run: snyk test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}