name: Example workflow for Gradle using Snyk
on: 
  push:
    branches: [main]
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: comprobacion  
        uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/gradle-jdk17@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
