name: Integración de Snyk con GitHub
on:
  push:
    branches: [main]

jobs:
  snyk:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Java 11
      uses: actions/setup-java@v1
      with:
        #Declaramos la versión de Java deseada
        java-version: '11'

    - name: Setup de nodejs
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar Snyk CLI
      run: npm install -g snyk
    - name: Analizar vulnerabilidades
      run: snyk test
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}